#!/bin/bash
#
# Camlp2: A m4 base preprocessor for ocaml
# (C) 2015 M E Leypold
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
# (probably nothing I should be proud of, quite to the contrary. I
#  hope that extension points will make this superflous)

set -o pipefail

MYPATH="$(dirname $0)"
case "$MYPATH" in
    /*)   ;;
     */*) MYPATH="$(cd "$MYPATH" && pwd)"   ;;
     *)   MYPATH="$(dirname "$(which "$0")")" ;;
esac

m4 -s -P "$MYPATH"/p2.m4 "$1" | sed 's|^#line *|#|' 
